# Generated by Django 4.2.6 on 2024-05-06 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=200)),
                ('fecha_creacion_rol', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion_rol', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=200)),
                ('numero_identificacion', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion_residencia', models.CharField(max_length=250)),
                ('numero_celular', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_creacion_persona', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_persona', models.DateTimeField(auto_now=True)),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.rol', verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioCIM')),
            ],
            options={
                'verbose_name': 'TecnicoDeMantenimiento',
                'verbose_name_plural': 'TecnicosDeMantenimientos',
            },
        ),
    ]
