# Generated by Django 4.2.6 on 2023-10-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'TecnicoDeMantenimiento', 'verbose_name_plural': 'TecnicosDeMantenimientos'},
        ),
    ]
