# Generated by Django 4.2.6 on 2023-10-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppUsuarios', '0001_initial'),
        ('AppComputadoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.TextField()),
                ('descripcion_actividad', models.TextField()),
                ('cumple', models.BooleanField()),
                ('no_cumple', models.BooleanField()),
                ('no_aplica', models.BooleanField()),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('fecha_creacion_actividad', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion_actividad', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(max_length=100)),
                ('fecha_mantenimiento', models.DateField()),
                ('observaciones', models.TextField()),
                ('fecha_creacion_mantenimiento', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion_mantenimiento', models.DateTimeField(auto_now=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.computador')),
                ('tecnico_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.persona', verbose_name='TecnicoDeMantenimientos')),
            ],
        ),
    ]
