# Generated by Django 4.2.6 on 2023-10-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='mantenimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppMantenimientos.mantenimiento', verbose_name='Mantenimiento'),
            preserve_default=False,
        ),
    ]
