# Generated by Django 4.2.6 on 2023-10-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMantenimientos', '0002_actividades_mantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='cumple',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='mantenimiento',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='no_aplica',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='no_cumple',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='actividad',
            field=models.ManyToManyField(to='AppMantenimientos.actividades', verbose_name='Actividades'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='cumple',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='no_aplica',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='no_cumple',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
