# Generated by Django 4.2.6 on 2024-05-06 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppResponsables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=200)),
                ('fecha_creacion_area', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_area', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno_monitor', models.CharField(max_length=50)),
                ('marca_monitor', models.CharField(max_length=100)),
                ('modelo_monitor', models.CharField(max_length=100)),
                ('serial_monitor', models.CharField(max_length=100)),
                ('descripcion_monitor', models.TextField()),
                ('fecha_adquisicion_monitor', models.DateField()),
                ('fecha_instalacion_monitor', models.DateField()),
                ('fecha_garantia_monitor', models.DateField()),
                ('registro_fotografico_monitor', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_requisicion_monitor', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_acta_salida_monitor', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_acta_recepcion_monitor', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_factura_monitor', models.ImageField(blank=True, null=True, upload_to='')),
                ('fecha_creacion_monitor', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_monitor', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_mouse', models.CharField(max_length=100)),
                ('modelo_mouse', models.CharField(max_length=100)),
                ('serial_mouse', models.CharField(max_length=100)),
                ('fecha_adquisicion_mouse', models.DateField()),
                ('fecha_instalacion_mouse', models.DateField()),
                ('fecha_garantia_mouse', models.DateField()),
                ('registro_fotografico_mouse', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficosMouses/')),
                ('foto_requisicion_mouse', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficosMouses/')),
                ('foto_acta_salida', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficosMouses/')),
                ('foto_acta_recepcion', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficosMouses/')),
                ('foto_factura', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficosMouses/')),
                ('fecha_creacion_mouse', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_mouse', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mouse',
                'verbose_name_plural': 'Mouses',
            },
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_teclado', models.CharField(max_length=100)),
                ('modelo_teclado', models.CharField(max_length=100)),
                ('serial_teclado', models.CharField(max_length=100)),
                ('fecha_adquisicion_teclado', models.DateField()),
                ('fecha_instalacion_teclado', models.DateField()),
                ('fecha_garantia_teclado', models.DateField()),
                ('registro_fotografico_teclado', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficoTeclados/')),
                ('foto_requisicion_teclado', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficoTeclados/')),
                ('foto_acta_salida_teclado', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficoTeclados/')),
                ('foto_acta_recepcion_teclado', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficoTeclados/')),
                ('foto_factura_teclado', models.ImageField(blank=True, null=True, upload_to='RegistroFotograficoTeclados/')),
                ('fecha_creacion_teclado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_teclado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teclado',
                'verbose_name_plural': 'Teclados',
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno_torre', models.CharField(max_length=50)),
                ('dominio_torre', models.CharField(max_length=200)),
                ('nombre_equipo', models.CharField(max_length=250)),
                ('marca_torre', models.CharField(max_length=50)),
                ('modelo_torre', models.CharField(max_length=50)),
                ('serial_torre', models.CharField(max_length=250)),
                ('direccion_ip_torre', models.CharField(max_length=15)),
                ('direccion_mac_torre', models.CharField(max_length=30)),
                ('descripcion_torre', models.TextField()),
                ('fecha_adquisicion_torre', models.DateField()),
                ('fecha_instalacion_torre', models.DateField()),
                ('fecha_garantia_torre', models.DateField()),
                ('registro_fotografico_torre', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_requisicion_torre', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_acta_salida_torre', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_acta_recepcion_torre', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_factura_torre', models.ImageField(blank=True, null=True, upload_to='')),
                ('fecha_creacion_torre', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_torre', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mouse',
                'verbose_name_plural': 'Torres',
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_trabajo', models.CharField(max_length=200)),
                ('fecha_creacion_workstation', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_workstation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Puesto de Trabajo',
                'verbose_name_plural': 'Puestos de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.ciudad')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Impresoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno_impresora', models.CharField(max_length=50)),
                ('nombre_impresora', models.CharField(max_length=100)),
                ('modelo_impresora', models.CharField(max_length=250)),
                ('serial_impresora', models.CharField(max_length=200)),
                ('descripcion_impresora', models.TextField()),
                ('fecha_adquisicion_impresora', models.DateField()),
                ('fecha_instalacion_impresora', models.DateField()),
                ('fecha_garantia_impresora', models.DateField()),
                ('registro_fotografico_impresora', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_requisicion_impresora', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_acta_salida_impresora', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_acta_recepcion_impresora', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_factura_impresora', models.ImageField(blank=True, null=True, upload_to='')),
                ('fecha_creacion_impresora', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_impresora', models.DateTimeField(auto_now=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.computador', verbose_name='Computador')),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
            },
        ),
        migrations.AddField(
            model_name='computador',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.monitor', verbose_name='Monitor'),
        ),
        migrations.AddField(
            model_name='computador',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.mouse', verbose_name='Mouse'),
        ),
        migrations.AddField(
            model_name='computador',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppResponsables.responsable', verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='computador',
            name='teclado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.teclado', verbose_name='Teclado'),
        ),
        migrations.AddField(
            model_name='computador',
            name='torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.torre', verbose_name='Torre'),
        ),
        migrations.AddField(
            model_name='computador',
            name='workstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.workstation', verbose_name='Workstation'),
        ),
        migrations.AddField(
            model_name='area',
            name='sedes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.sede'),
        ),
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno_accesorio', models.CharField(max_length=50)),
                ('nombre_accesorio', models.CharField(max_length=100)),
                ('serial_accesorio', models.CharField(max_length=100)),
                ('modelo_accessorio', models.CharField(max_length=50)),
                ('marca_accesorio', models.CharField(max_length=50)),
                ('descripcion_accesorio', models.TextField()),
                ('fecha_adquisicion_accesorio', models.DateField()),
                ('fecha_instalacion_accesorio', models.DateField()),
                ('fecha_garantia_accesorio', models.DateField()),
                ('registro_fotografico_accesorio', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_requisicion_accesorio', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_acta_salida_accesorio', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_acta_recepcion_accesorio', models.ImageField(blank=True, null=True, upload_to='')),
                ('foto_factura_accesorio', models.ImageField(blank=True, null=True, upload_to='')),
                ('fecha_creacion_accesorio', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_accesorio', models.DateTimeField(auto_now=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.computador', verbose_name='Computador')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
            },
        ),
    ]
