# Generated by Django 4.2.6 on 2023-10-26 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppComputadoras', '0003_accesorios_computador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstation',
            name='area',
        ),
        migrations.AddField(
            model_name='computador',
            name='workstation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.workstation', verbose_name='Workstation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computador',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComputadoras.area', verbose_name='Area'),
        ),
    ]
