# Generated by Django 4.2.6 on 2023-10-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResponsables', '0001_initial'),
        ('AppComputadoras', '0004_remove_workstation_area_computador_workstation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='responsable',
        ),
        migrations.AddField(
            model_name='computador',
            name='responsable',
            field=models.ManyToManyField(to='AppResponsables.responsable', verbose_name='Responsable'),
        ),
    ]
