# Generated by Django 4.2.6 on 2023-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComputadoras', '0005_remove_computador_responsable_computador_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='foto_acta_recepcion_accesorio',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accesorios',
            name='foto_acta_salida_accesorio',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accesorios',
            name='foto_factura_accesorio',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accesorios',
            name='foto_requisicion_accesorio',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accesorios',
            name='registro_fotografico_accesorio',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='foto_acta_recepcion_impresora',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='foto_acta_salida_impresora',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='foto_factura_impresora',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='foto_requisicion_impresora',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='registro_fotografico_impresora',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='foto_acta_recepcion_monitor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='foto_acta_salida_monitor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='foto_factura_monitor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='foto_requisicion_monitor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='registro_fotografico_monitor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='foto_acta_recepcion',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='foto_acta_salida',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='foto_factura',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='foto_requisicion_mouse',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='registro_fotografico_mouse',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='foto_acta_recepcion_teclado',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='foto_acta_salida_teclado',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='foto_factura_teclado',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='foto_requisicion_teclado',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='registro_fotografico_teclado',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='torre',
            name='foto_acta_recepcion_torre',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='torre',
            name='foto_acta_salida_torre',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='torre',
            name='foto_factura_torre',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='torre',
            name='foto_requisicion_torre',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='torre',
            name='registro_fotografico_torre',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
